Repository boostcampwm-2021/iOS03-Routinus, pull requests merged in 2021-11, with the labels that each got.

#20 [공통] 프로젝트 생성
  .gitignore
  Routinus/.swiftlint.yml
  Routinus/Podfile
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Routinus/Routinus.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Routinus/Routinus.xcworkspace/contents.xcworkspacedata
  Routinus/Routinus.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Routinus/Routinus/AppDelegate.swift
  Routinus/Routinus/Assets.xcassets/AccentColor.colorset/Contents.json
  Routinus/Routinus/Assets.xcassets/AppIcon.appiconset/Contents.json
  Routinus/Routinus/Assets.xcassets/Contents.json
  Routinus/Routinus/Base.lproj/LaunchScreen.storyboard
  Routinus/Routinus/Base.lproj/Main.storyboard
  Routinus/Routinus/Info.plist
  Routinus/Routinus/SceneDelegate.swift
  Routinus/Routinus/ViewController.swift
Labels: ✨feature

#21 [런치스크린] 앱 실행시 루티너스 로고 표시
  Routinus/Routinus/Assets.xcassets/Logo.imageset/Contents.json
  Routinus/Routinus/Assets.xcassets/Logo.imageset/routinous title.png
  Routinus/Routinus/Base.lproj/LaunchScreen.storyboard
Labels: ✨feature

#23 [공통] Firebase 설정
  .gitignore
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Routinus/RoutinusNetwork/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusNetwork/DTO/HomeUserDTO.swift
  Routinus/RoutinusNetwork/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusNetwork/DTO/UserDTO.swift
  Routinus/RoutinusNetwork/GoogleService-Info.plist
  Routinus/RoutinusNetwork/RoutinusNetwork.h
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#24 [공통] MVVM + Coordinator를 기반으로 시스템을 구축
  Routinus/.swiftlint.yml
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AppCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/Coordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Application/SceneDelegate.swift
  Routinus/Routinus/Domain/Entity/ArchievementInfo.swift
  Routinus/Routinus/Domain/Entity/ChllangeInfo.swift
  Routinus/Routinus/Domain/Entity/UserInfo.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Base.lproj/Main.storyboard
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Create/CreateController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Resources/Info.plist
Labels: ✨feature

#25 [홈화면] UI 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Routinus/Routinus/Presentation/Home/Calendar/DateCell.swift
  Routinus/Routinus/Presentation/Home/Calendar/DateHeader.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/RoutineCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/DayColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/ETCColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/ExerciseColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/FinanceColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/LifeStyleColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/MainColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/SaturdayColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/SelfDevelpmentColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/SundayColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/hobbyColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@3x.png
Labels: ✨feature

#28 [홈 화면] RoutinusNetwork 수정
  Routinus/RoutinusNetwork/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusNetwork/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusNetwork/DTO/UserDTO.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#29 [공통, 홈 화면] RoutinusNetwork AchievementInfo 수정
  Routinus/RoutinusNetwork/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#30 [공통, 홈화면] Usecase 및 ViewModel 구성
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/AppDelegate.swift
  Routinus/Routinus/Application/Coordinator/AppCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Domain/Entity/AchievementInfo.swift
  Routinus/Routinus/Domain/Entity/ArchievementInfo.swift
  Routinus/Routinus/Domain/Entity/ChllangeInfo.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Domain/Entity/UserInfo.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Extensions/Date+Extension.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/RoutineCell.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#31 [홈화면] 화면 UI작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Home/Calendar/CalendarDelegate.swift
  Routinus/Routinus/Presentation/Home/Calendar/Date+Extensions.swift
  Routinus/Routinus/Presentation/Home/Calendar/DateCell.swift
  Routinus/Routinus/Presentation/Home/Calendar/DateHeader.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/RoutineCell.swift
Labels: ✨feature

#32 [홈화면] UI 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Domain/Entity/AchievementInfo.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Home/Calendar/CalendarDelegate.swift
  Routinus/Routinus/Presentation/Home/Calendar/Date+Extensions.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/RoutineCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@x1.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@x2-1.png
  Routinus/Routinus/Resources/Assets.xcassets/chart.white.imageset/chart.white@x3.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/highlighter.black.imageset/highlighter.black@x1.png
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#33 [홈 화면] Coordinator 이동 설정
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Resources/Assets.xcassets/seed.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/seed.imageset/pngwing.com.png
Labels: ✨feature

#35 [홈 화면] 캘린더 UI 수정
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/RoutineCell.swift
Labels: ✨feature

#37 [공통] Coordinator 리팩토링
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AppCoordinator.swift
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/Coordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Domain/Entity/AchievementInfo.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
Labels: ✨feature

#77 [공통] 앱 아이콘 추가
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-40.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-72.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-76.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-small-50.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-small-50@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-small.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-small@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon-small@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/icon@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/notification-icon@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/notification-icon@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad.png
  Routinus/Routinus/Resources/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad@2x.png
Labels: ✨feature

#78 [홈 화면] 강제 언래핑 수정
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
Labels: ♻️refactor

#79 [공통] RoutinusNetwork -> RoutinusDatabase로 이름 변경
  .gitignore
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/AppDelegate.swift
  Routinus/Routinus/Domain/Entity/AchievementInfo.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/RoutinusDatabase/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusDatabase/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/GoogleService-Info.plist
  Routinus/RoutinusDatabase/RoutinusDatabase.h
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusNetwork/DTO/HomeUserDTO.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.h
Labels: ♻️refactor

#80 [refactor] Coordinator를 RoutinusCoordinator로 이름 변경
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AppCoordinator.swift
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/Coordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/RoutinusCoordinator.swift
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
Labels: ♻️refactor

#81 [챌린지 화면] UI수정
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/CollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
Labels: ✨feature

#83 [챌린지 화면] ChallengeFetchUsecase 구성
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
Labels: ✨feature

#84 [챌린지 화면] database 구성
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#82 [챌린지 화면] viewModel 및 Entity설정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Entity/RecommendChallenge.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButton.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeRecommendCell.swift
Labels: ✨feature

#86 [챌린지 화면] domain 로직 추가
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
Labels: ✨feature

#85 [홈 화면] Repository 구축
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Data/HomeRepository.swift
  Routinus/Routinus/Data/RoutinusRepository.swift
  Routinus/Routinus/Data/UserNameFactory.swift
  Routinus/Routinus/Domain/Usecase/HomeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#101 [홈 화면] HomeViewModel protocol name 변경 및 오늘루틴 +Button delegate 적용
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/TodayRoutineView.swift
Labels: ♻️refactor

#102 [챌린지 화면] 버튼 이미지 크기 수정 및 화면 이동
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButton.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeRecommendCell.swift
Labels: ✨feature

#104 [챌린지 화면] category Button 터치 시 이동
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButton.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButtonTapGesture.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
Labels: ✨feature

#105 [챌린지 화면] Coordinator 설정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
Labels: ✨feature

#106 [챌린지 화면] 90% 구현 완료
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Domain/Entity/RecommendChallenge.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Challenge/CollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButton.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButtonTapGesture.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeRecommendCell.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#107 [챌린지 화면] Repository 적용
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
Labels: ✨feature

#108 [챌린지 화면] 화면 이동시 돋보기 버튼 표시 수정
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
Labels: 🐛bug

#109 [챌린지 화면] Repository 적용 및 화면 이동시 돋보기 버튼 표시 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
Labels: ✨feature, 🐛bug

#110 [공통] Entity 통합 및 Database API 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Entity/Category.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Entity/RecommendChallenge.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButtonTapGesture.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeRecommendCell.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/RoutineCell.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#112 [챌린지 검색화면] Search UI작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/cell/SearchChallengeCell.swift
  Routinus/Routinus/Presentation/Search/cell/SearchCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularTermCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/SearchTermColor.colorset/Contents.json
Labels: ✨feature

#113 [공통] Challenge Entity 수정
  Routinus/Routinus/Domain/Entity/Challenge.swift
Labels: ♻️refactor

#114 [챌린지 검색화면] 검색화면 VM, Usecase, Repo 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#115 [공통] 스위프트 린트 에러 수정
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Data/HomeRepository.swift
  Routinus/Routinus/Data/UserNameFactory.swift
  Routinus/Routinus/Domain/Entity/AchievementInfo.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButtonTapGesture.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeRecommendCell.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/Calendar/CalendarDelegate.swift
  Routinus/Routinus/Presentation/Home/Subviews/Calendar/DateCell.swift
  Routinus/Routinus/Presentation/Home/Subviews/Calendar/DateHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/Continuity/ContinuityView.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/RoutineCell.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/TodayRoutineView.swift
  Routinus/RoutinusDatabase/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusDatabase/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#116 [챌린지 추가 화면] ViewModel, Usecase, Database 작업 + DTO Initializer 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/RoutinusRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusDatabase/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#117 [챌린지 검색 화면] Touch Delegate 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/cell/PopularTermButton.swift
  Routinus/Routinus/Presentation/Search/cell/SearchChallengeCell.swift
  Routinus/Routinus/Presentation/Search/cell/SearchCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularTermCell.swift
Labels: ✨feature

#118 [챌린지 추가 화면] UI 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Create/CreateController.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthImageRegister/CreateAuthImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthMethod/CreateAuthMethodView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategory/CreateCategoryView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateDesc/CreateDescView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateImageRegister/CreateImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateTitle/CreateTitleView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeek/CreateWeekView.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
Labels: ✨feature

#120 [챌린지검색 화면] 키보드 내리기 및 인기검색어 SearchBar연동
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ✨feature

#121 [챌린지검색 화면] 키보드 외부 터치시 키보드 hide
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ✨feature

#123 [챌린지 검색화면] 검색기능 구현
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#122 [챌린지 추가 화면] 챌린지 추가 화면 임시 구현
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/RoutinusRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Create/CreateController.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Create/Delegates/CreateImagePickerDelegate.swift
  Routinus/Routinus/Presentation/Create/Delegates/CreateSubviewDelegate.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthMethodView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategoryView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateIntroductionView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateTitleView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeekView.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Resources/Info.plist
  Routinus/RoutinusDatabase/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#126 [홈 화면] 테이블 swipe 시 인증하기 버튼 UI 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Extensions/UIImage+Extensions.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
Labels: ♻️refactor

#124 [챌린지검색 화면] Coordinator 설정
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
Labels: ✨feature

#125 [챌린지검색 화면] SearchBarView 클래스 분리 및 navigationBar 높이 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/Subviews/SearchBarContainerView.swift
Labels: 🐛bug

#127 [챌린지검색 화면] 변수 및 파일명 리펙토링
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Entity/PopularKeyword.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularKeywordButton.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularKeywordCell.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularTermCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/SearchKeywordColor.colorset/Contents.json
Labels: ✨feature

#128 [챌린지 검색화면] 검색 기능 수정
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#129 [챌린지검색 화면] 리펙토링
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularKeywordCell.swift
Labels: ✨feature

#130 [챌린지 검색 화면] 임시 구현
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Entity/PopularKeyword.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/Routinus/Presentation/Search/Subviews/SearchBarContainerView.swift
  Routinus/Routinus/Presentation/Search/cell/SearchChallengeCell.swift
  Routinus/Routinus/Presentation/Search/cell/SearchCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularKeywordButton.swift
  Routinus/Routinus/Presentation/Search/cell/SearchPopularKeywordCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/SearchKeywordColor.colorset/Contents.json
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#133 [공통] 3주차 데모 전 수정
  Routinus/Podfile
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/CollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateTitleView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/cell/SearchChallengeCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/AuthView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/AuthView.imageset/auth.png
  Routinus/Routinus/Resources/Assets.xcassets/ChallengeDetailView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/ChallengeDetailView.imageset/detail.png
  Routinus/Routinus/Resources/Assets.xcassets/ManageView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/ManageView.imageset/manage.png
  Routinus/Routinus/Resources/Assets.xcassets/MyPageView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/MyPageView.imageset/mypage.png
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#136 [챌린지 화면] UI 리팩토링
  Routinus/Routinus/Presentation/Challenge/cell/CategoryButton.swift
  Routinus/Routinus/Presentation/Challenge/cell/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/RoutineCell.swift
  Routinus/Routinus/Presentation/Search/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/cell/SearchChallengeCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/check.calendar.imageset/calendar@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/SelfDevelopmentColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/dumbbell.imageset/dumbbell@3x.png
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#137 [홈 화면] 루틴 cell에 swipe 표시 추가
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/RoutinusRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutine/RoutineCell.swift
Labels: ♻️refactor

#143 [공통] Firebase SDK 제거하고 Rest API로 마이그레이션
  Routinus/.swiftlint.yml
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/AppDelegate.swift
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/HomeRepository.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Entity/Achievement.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/Calendar/CalendarDelegate.swift
  Routinus/RoutinusDatabase/DTO/AchievementDTO.swift
  Routinus/RoutinusDatabase/DTO/AchievementInfoDTO.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/DTO/ParticipationDTO.swift
  Routinus/RoutinusDatabase/DTO/TodayRoutineDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/GoogleService-Info.plist
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ♻️refactor

#138 [공통] 화면이동 수정
  Routinus/Routinus/Application/Coordinator/AppCoordinator.swift
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/RoutinusCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
Labels: ♻️refactor

#141 [홈화면] ViewModel UnitTests
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/RoutinusTests/MockDatas/HomeCreatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/HomeFetchableUsecaseMock.swift
  Routinus/RoutinusTests/ViewModelTests/HomeViewModelTests.swift
Labels: ✨feature

#139 [챌린지 추가 화면] 챌린지 기간이 53주가 넘어가면 53주로 고정
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeekView.swift
Labels: ✨feature

#140 [챌린지 추가 화면] 챌린지 fetch & update 로직
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Data/UpdateRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature

#182 [챌린지 검색 화면] 리펙토링
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchPopularKeywordCell.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/Routinus/Presentation/Search/Subviews/PopularKeywordButton.swift
  Routinus/Routinus/Presentation/Search/Subviews/SearchBarContainerView.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/SearchKeywordColor.colorset/Contents.json
Labels: ♻️refactor

#183 [공통] ViewModel Signal 네이밍 수정 및 화면 표시 방안 수정
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/RoutinusTests/MockDatas/HomeFetchableUsecaseMock.swift
  Routinus/RoutinusTests/ViewModelTests/HomeViewModelTests.swift
Labels: ♻️refactor

#184 [챌린지 검색 화면] Cell 기본 이미지 placeholder 제거
  Routinus/Routinus/Presentation/Search/Cells/SearchChallengeCell.swift
Labels: ♻️refactor

#192 [챌린지 화면] 카테고리 추가
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCell.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/EmotionManageColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/ReadColor.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/StudyColor.colorset/Contents.json
Labels: ✨feature

#191 [챌린지 추가 화면] RoutinusDatabase 수정에 따른 fetch & update 로직 수정
  Routinus/Routinus/Data/UpdateRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#187 [공통] RoutinusImageManager 구현
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchChallengeCell.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusImageManager/RoutinusImageManager.h
  Routinus/RoutinusImageManager/RoutinusImageManager.swift
Labels: ✨feature

#190 [공통] NavigationBar 뒤로가기 버튼 및 Large title 수정
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ✨feature, 🐛bug, ♻️refactor

#200 [챌린지 관리 화면] 관리 화면 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Data/ManageRepository.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Usecase/ManageFetchUsecase.swift
  Routinus/Routinus/Presentation/Manage/ManageCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#202 [인증 화면] UI 중간 작업 및 Common 폴더 추가
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/Subviews/AuthButton.swift
  Routinus/Routinus/Presentation/Auth/Subviews/PreviewView.swift
  Routinus/Routinus/Presentation/Common/AuthMethodView.swift
Labels: ✨feature

#193 [홈 화면] 캘린더 리팩토링
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Entity/Calendar.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Home/Cells/DateCell.swift
  Routinus/Routinus/Presentation/Home/Cells/DateHeader.swift
  Routinus/Routinus/Presentation/Home/Delegates/CalendarDelegate.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
Labels: ♻️refactor

#201 [공통] RoutinusImageManager 기능 구현
  Routinus/.swiftlint.yml
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/UpdateRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Extensions/UIImage+Extensions.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusImageManager/RoutinusImageManager.swift
Labels: ✨feature, ♻️refactor

#205 [챌린지 검색 화면] 이미지 캐싱 구현
  Routinus/Podfile
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchChallengeCell.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusImageManager/RoutinusImageManager.swift
Labels: ✨feature, ♻️refactor

#208 [공통] Usecase, Repository refactor 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/AchievementRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/CreateRepository.swift
  Routinus/Routinus/Data/HomeRepository.swift
  Routinus/Routinus/Data/ImageRepository.swift
  Routinus/Routinus/Data/ManageRepository.swift
  Routinus/Routinus/Data/SearchRepository.swift
  Routinus/Routinus/Data/TodayRoutineRepository.swift
  Routinus/Routinus/Data/UpdateRepository.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/AchievementFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/HomeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ImageFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ImageSaveUsecase.swift
  Routinus/Routinus/Domain/Usecase/ManageFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/SearchFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/TodayRoutineFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserFetchUsecase.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
Labels: ♻️refactor

#207 [챌린지 상세 화면] UI 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Common/AuthMethodView.swift
  Routinus/Routinus/Presentation/Common/Cells/ChallengeCollectionViewCell.swift
  Routinus/Routinus/Presentation/Common/Subviews/AuthMethodView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/Subviews/InformationView.swift
  Routinus/Routinus/Presentation/Detail/Subviews/ParticipantButton.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ✨feature

#209 [홈 화면] 캘린더 관련 이슈 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
Labels: ♻️refactor

#212 [인증 화면] ViewModel 및 Usecase, Repository 중간 구현
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#213 [챌린지 검색 화면] 멘토링 사항 수정 및 검색 화면 fetch 수정
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/Layouts/CollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Common/Cells/ChallengeCollectionViewCell.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
Labels: ♻️refactor

#214 [인증 화면] 인증화면 ui 작업
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/Subviews/PreviewView.swift
Labels: ✨feature

#215 [공통] SnapKit 삭제
  Routinus/Podfile
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Entity/User.swift
  Routinus/Routinus/Extensions/UIView+Extensions.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCell.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCell.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/Layouts/CollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Challenge/Subviews/CategoryButton.swift
  Routinus/Routinus/Presentation/Common/Cells/ChallengeCollectionViewCell.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthMethodView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategoryView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateIntroductionView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateTitleView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeekView.swift
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Presentation/Home/Subviews/ContinuityView.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Presentation/Manage/ManageCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchHeader.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchPopularKeywordCell.swift
  Routinus/Routinus/Presentation/Search/Layouts/SearchCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ♻️refactor

#217 [인증 화면] 인증화면 View 구성 및 challenge_auth database 구성
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Entity/ChallengeAuth.swift
  Routinus/Routinus/Domain/Usecase/ChallengeAuthCreateUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Auth/Subviews/AuthButton.swift
  Routinus/Routinus/Presentation/Auth/Subviews/PreviewView.swift
  Routinus/Routinus/Presentation/Common/Subviews/AuthMethodView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeekView.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/RoutinusDatabase/DTO/ChallengeAuthDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#218 [공통] async/await 제거
  Routinus/Routinus/Data/AchievementRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/TodayRoutineRepository.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/AchievementFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/TodayRoutineFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserFetchUsecase.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusTests/ViewModelTests/HomeViewModelTests.swift
Labels: ♻️refactor

#219 [챌린지 화면] 인기 챌린지 swipe 시 autoLayout 충돌 수정
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeHeader.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCell.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
Labels: ✨feature

#220 [챌린지 상세화면] 챌린지 상세화면 1차 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/ParticipationRepository.swift
  Routinus/Routinus/Domain/Entity/Participation.swift
  Routinus/Routinus/Domain/Usecase/ParticipationCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ParticipationFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserFetchUsecase.swift
  Routinus/Routinus/Presentation/Common/Subviews/AuthMethodView.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Detail/Subviews/InformationView.swift
  Routinus/Routinus/Presentation/Detail/Subviews/ParticipantButton.swift
  Routinus/RoutinusDatabase/DTO/ParticipationDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#222 [챌린지 추가화면] iOS 14 이상이면 UImenu, 이하는 actionSheet로 동작
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/Delegates/CreateSubviewDelegate.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategoryView.swift
Labels: ♻️refactor

#223 [챌린지 관리 화면] cell 이미지 출력
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Presentation/Manage/Layouts/ManageCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ✨feature

#225 [홈 화면] 오늘 루틴 fetch 로직 수정
  Routinus/Routinus/Domain/Entity/TodayRoutine.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ♻️refactor

#224 [챌린지 추가 화면] 시뮬레이터에서 카메라 접근 못하도록 수정
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
Labels: ♻️refactor

#226 [홈 화면] 실행 시 today achievement document 생성
  Routinus/.swiftlint.yml
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#227 [챌린지 상세 화면] 인증 fetch 로직 & 인증하기 화면 연결
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/SearchCoordinator.swift
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeAuthCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeAuthFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/ParticipationFetchUsecase.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Detail/Subviews/ParticipantButton.swift
  Routinus/RoutinusDatabase/DTO/ChallengeAuthDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#228 [공통] localization 작업
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Presentation/Auth/Subviews/AuthButton.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategoryView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Detail/Subviews/ParticipantButton.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Presentation/Home/Subviews/ContinuityView.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature

#229 [인증 화면] 인증하기 클릭 시 auth_count, achievement_count 증가
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Data/AchievementRepository.swift
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Data/ParticipationRepository.swift
  Routinus/Routinus/Domain/Usecase/AchievementFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/AchievementUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ParticipationUpdateUsecase.swift
  Routinus/Routinus/Extensions/Date+Extensions.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Auth/Subviews/PreviewView.swift
  Routinus/RoutinusDatabase/DTO/AchievementDTO.swift
  Routinus/RoutinusDatabase/DTO/ParticipationDTO.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ✨feature

#238 [RoutinusDatabase] Query 및 DTO 개선
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/RoutinusDatabase/DTO/AchievementDTO.swift
  Routinus/RoutinusDatabase/DTO/ChallengeAuthDTO.swift
  Routinus/RoutinusDatabase/DTO/ChallengeDTO.swift
  Routinus/RoutinusDatabase/DTO/Fields.swift
  Routinus/RoutinusDatabase/DTO/ParticipationDTO.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/Query/AchievementQuery.swift
  Routinus/RoutinusDatabase/Query/AuthQuery.swift
  Routinus/RoutinusDatabase/Query/ChallengeQuery.swift
  Routinus/RoutinusDatabase/Query/ParticipationQuery.swift
  Routinus/RoutinusDatabase/Query/UserQuery.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
  Routinus/RoutinusDatabase/RoutinusQuery.swift
Labels: ♻️refactor

#241 [홈 화면] cell swipe 후 원래대로 돌아오도록 수정
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
Labels: ♻️refactor

#242 [공통] tabbar Icon 수정
  Routinus/Routinus/Application/Coordinator/TabBarCoordinator.swift
  Routinus/Routinus/Resources/Assets.xcassets/Icons/challenge.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/Icons/challenge.imageset/challenge@x1.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/challenge.imageset/challenge@x2.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/challenge.imageset/challenge@x3.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/chart.white.imageset/chart.white@x1.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/chart.white.imageset/chart.white@x2-1.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/chart.white.imageset/chart.white@x3.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/highlighter.black.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/Icons/highlighter.black.imageset/highlighter.black@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/highlighter.black.imageset/highlighter.black@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/highlighter.black.imageset/highlighter.black@x1.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/MainColor.colorset/Contents.json
Labels: ♻️refactor

#243 [홈 화면] Calendar UI수정
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/0-20.imageset/0-20.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/0-20.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/100.imageset/100.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/100.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/20-40.imageset/20-40.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/20-40.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/40-70.imageset/40-70.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/40-70.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/70-99.imageset/70-99.png
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/70-99.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/Calendar/achievement/Contents.json
Labels: ♻️refactor

#239 [공통] 파일 이름 일관성있게 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCollectionViewCell.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCollectionViewCell.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/Layouts/ChallengeCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Search/Cells/SearchPopularKeywordCollectionViewCell.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: ♻️refactor

#246 [챌린지 추가 화면] 이미지 관련 issue 대응
  Routinus/Routinus/Extensions/UIImage+Extensions.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthImageRegisterView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateImageRegisterView.swift
Labels: ♻️refactor

#247 [리펙토링] 데이터 패치 동기화 작업
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
Labels: 🐛bug

#251 [홈 화면] 챌린지 추가 후 데이터 패치
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
Labels: 🐛bug

#249 [챌린지 관리 화면] 내가 개설한 챌린지 -> My Challenges로 변경
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Presentation/Common/Subviews/AddChallengeView.swift
  Routinus/Routinus/Presentation/Manage/Cells/ManageAddCollectionViewCell.swift
  Routinus/Routinus/Presentation/Manage/Cells/ManageCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Manage/Layouts/ManageCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature, ♻️refactor

#253 [RoutinusImageManager] 챌린지 ID를 기준으로 캐시 삭제할 수 있도록 개선
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/RoutinusImageManager/RoutinusImageManager.swift
Labels: ♻️refactor

#252 [챌린지 검색 화면] 검색창 debounce로 변경
  Routinus/Routinus/Presentation/Search/SearchViewModel.swift
Labels: ♻️refactor

#250 [인증 화면] autolayout -> UIView extension 변경 및 continuityDay 업데이트
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/UserUpdateUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Auth/Subviews/AuthButton.swift
  Routinus/RoutinusDatabase/DTO/UserDTO.swift
  Routinus/RoutinusDatabase/Query/UserQuery.swift
  Routinus/RoutinusDatabase/RoutinusDatabase.swift
Labels: ✨feature, ♻️refactor

#254 [챌린지 추가 화면] 챌린지 update 로직 적용
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Entity/Challenge.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateAuthMethodView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateCategoryView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateIntroductionView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateTitleView.swift
  Routinus/Routinus/Presentation/Create/Subviews/CreateWeekView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
Labels: ✨feature

#267 [챌린지 관리 화면] 챌린지 추가 버튼 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Manage/Cells/ManageAddCollectionViewCell.swift
  Routinus/Routinus/Presentation/Manage/Layouts/ManageCollectionViewLayouts.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Manage/Subviews/ManageAddChallengeView.swift
Labels: ♻️refactor

#268 [홈 화면] 캘린더 날짜 색상 이슈 수정
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
Labels: 🐛bug

#266 [챌린지 상세 화면] 챌린지 참여해도 참여자 늘어나지 않는 문제 해결
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/RoutinusNetwork/Query/ChallengeQuery.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: 🐛bug

#269 [챌린지 추가 화면] 챌린지 이미지를 변경할 때 이미지가 없어지는 문제 해결
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/ImageRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ImageUpdateUsecase.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: 🐛bug

#275 [홈 화면] 오늘 루틴 없을 시 대체 텍스트 표시
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature, ♻️refactor

#274 [홈화면] 런치스크린 설정 및 데이터 패치 리펙토링
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/AppDelegate.swift
  Routinus/Routinus/Extensions/UIImage+Extensions.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/ContinuityView.swift
  Routinus/Routinus/Presentation/Launch/Base.lproj/LaunchScreen.storyboard
  Routinus/Routinus/Presentation/Launch/Subviews/LaunchVIew.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Resources/Assets.xcassets/AuthView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/AuthView.imageset/auth.png
  Routinus/Routinus/Resources/Assets.xcassets/ChallengeDetailView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/ChallengeDetailView.imageset/detail.png
  Routinus/Routinus/Resources/Assets.xcassets/Logo.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/Logo.imageset/logo@x1.png
  Routinus/Routinus/Resources/Assets.xcassets/Logo.imageset/logo@x2.png
  Routinus/Routinus/Resources/Assets.xcassets/Logo.imageset/logo@x3.png
  Routinus/Routinus/Resources/Assets.xcassets/Logo.imageset/routinous title.png
  Routinus/Routinus/Resources/Assets.xcassets/ManageView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/ManageView.imageset/manage.png
  Routinus/Routinus/Resources/Assets.xcassets/MyPageView.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/MyPageView.imageset/mypage.png
Labels: ✨feature, 🐛bug

#276 [마이페이지] 마이페이지 구현
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Data/RoutinusRepository.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/UserFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserUpdateUsecase.swift
  Routinus/Routinus/Presentation/MyPage/Delegates/MyPageUserNameUpdatableDelegate.swift
  Routinus/Routinus/Presentation/MyPage/MyPageDeveloperViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewModel.swift
  Routinus/Routinus/Presentation/MyPage/Subviews/MyPageProfileView.swift
  Routinus/RoutinusNetwork/Query/UserQuery.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#284 [챌린지 상세 화면] 챌린지 참여하기 버튼을 눌렀을 때 acheievement 테이블의 Total count 증가
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Data/AchievementRepository.swift
  Routinus/Routinus/Domain/Usecase/AchievementUpdateUsecase.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/RoutinusNetwork/Query/AchievementQuery.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#285 [챌린지 화면] 인기챌린지 cell 배경 지정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCollectionViewCell.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCollectionViewCell.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Challenge/Subviews/ChallengeCategoryIconView.swift
Labels: ✨feature, ♻️refactor

#286 [마이페이지] Coordinator를 통해 모달 호출하도록 수정
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewModel.swift
Labels: ♻️refactor

#288 [홈화면] 초기 데이터 설정 로직 변경 및 오늘루틴셀 인증완료 표시
  Routinus/Routinus/Application/AppDelegate.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/UserCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserFetchUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserUpdateUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/TodayRoutineView.swift
  Routinus/Routinus/Presentation/Launch/Subviews/LaunchVIew.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewModel.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature, ♻️refactor

#292 [인증화면] 인증사진 워터마크 유저닉네임 추가 및 Storage 저장 naming 수정
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/ImageRepository.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#291 [홈 화면] progressbar 애니메이션 임시 적용
  Routinus/Routinus/Presentation/Home/Cells/RoutineTableViewCell.swift
Labels: ✨feature

#293 [챌린지 관리 화면] 화살표 애니메이션 구현
  Routinus/Routinus/Presentation/Manage/Cells/ManageCollectionViewHeader.swift
Labels: ✨feature, ♻️refactor

#295 [홈 화면/챌린지 상세 화면] 캘린더 데이터 패치 및 상세화면 AutoLayout 수정
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCollectionViewCell.swift
  Routinus/Routinus/Presentation/Common/Subviews/AuthMethodView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Detail/Subviews/InformationView.swift
  Routinus/Routinus/Presentation/Detail/Subviews/ParticipantButton.swift
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarHeader.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Presentation/Home/Subviews/ContinuityView.swift
  Routinus/Routinus/Resources/Assets.xcassets/Icons/check.calendar.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/Icons/check.calendar.imageset/calendar.svg
  Routinus/Routinus/Resources/Assets.xcassets/Icons/check.calendar.imageset/calendar@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/check.calendar.imageset/calendar@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/check.calendar.imageset/calendar@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/dumbbell.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/Icons/dumbbell.imageset/dumbbell.svg
  Routinus/Routinus/Resources/Assets.xcassets/Icons/dumbbell.imageset/dumbbell@1x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/dumbbell.imageset/dumbbell@2x.png
  Routinus/Routinus/Resources/Assets.xcassets/Icons/dumbbell.imageset/dumbbell@3x.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/1.imageset/0-20.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/1.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/2.imageset/20-40.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/2.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/3.imageset/40-70.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/3.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/4.imageset/70-99.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/4.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/5.imageset/100%.png
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/5.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achieveIcons/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/0-20.imageset/0-20.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/0-20.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/100.imageset/100.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/100.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/20-40.imageset/20-40.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/20-40.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/40-70.imageset/40-70.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/40-70.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/70-99.imageset/70-99.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/70-99.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/LightGray.colorset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/colors/MainColor0.5.colorset/Contents.json
  Routinus/RoutinusNetwork/Query/ChallengeQuery.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: 🐛bug, ♻️refactor

#294 [챌린지 추가 화면] 스크롤 개선
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
Labels: 🐛bug, ♻️refactor

#296 [챌린지 화면] 네비게이션바 없애기 및 Localizing
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeCategoryCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Challenge/Cells/ChallengeRecommendCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/Delegates/ChallengeCategoryHeaderDelegate.swift
  Routinus/Routinus/Presentation/Challenge/Delegates/ChallengeRecommendHeaderDelegate.swift
  Routinus/Routinus/Presentation/Challenge/Layouts/ChallengeCollectionViewLayouts.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ♻️refactor

#300 [챌린지 화면, 검색 화면] 데이터 요청 부분 endDate 적용
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
Labels: ✨feature

#297 [챌린지 상세 화면, 인증 목록 화면] 상세화면 View 추가 + 인증 목록 사진 불러오기
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthListCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeAuthFetchUsecase.swift
  Routinus/Routinus/Extensions/UICollectionView+Extensions.swift
  Routinus/Routinus/Presentation/AuthImages/AuthImagesViewController.swift
  Routinus/Routinus/Presentation/AuthImages/AuthImagesViewModel.swift
  Routinus/Routinus/Presentation/AuthImages/Cells/AuthImagesCollectionViewCell.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Detail/Subviews/DetailAuthDisplayListView.swift
  Routinus/Routinus/Presentation/Detail/Subviews/DetailAuthDisplayView.swift
  Routinus/RoutinusNetwork/Query/AuthQuery.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature

#303 [챌린지 생성 화면] 최초 실행시 로딩 느린 문제 해결
  Routinus/Routinus/Application/AppDelegate.swift
Labels: 🐛bug

#305 [홈 화면] 캘린더 부연 설명 추가
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Presentation/Home/Cells/DateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarExplanationViewController.swift
  Routinus/Routinus/Presentation/Home/Subviews/CalendarView.swift
  Routinus/Routinus/Resources/Assets.xcassets/achievement/1-19.imageset/0-20.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/1-19.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/20-39.imageset/20-40.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/20-39.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/40-65.imageset/40-70.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/40-65.imageset/Contents.json
  Routinus/Routinus/Resources/Assets.xcassets/achievement/66-99.imageset/70-99.png
  Routinus/Routinus/Resources/Assets.xcassets/achievement/66-99.imageset/Contents.json
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature

#306 [공통] swipe시 패치 기능 적용
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/AuthImages/AuthImagesViewController.swift
  Routinus/Routinus/Presentation/AuthImages/AuthImagesViewModel.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ♻️refactor

#307 [전체] 데이터 동기화 로직 개선
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ChallengeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/CreateCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Application/Coordinator/ManageCoordinator.swift
  Routinus/Routinus/Data/AchievementRepository.swift
  Routinus/Routinus/Data/ChallengeAuthRepository.swift
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Data/ParticipationRepository.swift
  Routinus/Routinus/Data/UserRepository.swift
  Routinus/Routinus/Domain/Usecase/AchievementUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeAuthCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ChallengeUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ParticipationCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ParticipationUpdateUsecase.swift
  Routinus/Routinus/Domain/Usecase/UserUpdateUsecase.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewModel.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/Manage/ManageViewModel.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: ✨feature, 🐛bug, ♻️refactor

#309 [챌린지 상세 화면/인증 화면] 이미지 바로 안뜨는 이슈 수정
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Auth/AuthViewModel.swift
  Routinus/Routinus/Presentation/Common/ImagePinchViewController.swift
  Routinus/Routinus/Presentation/Common/Subviews/AuthMethodView.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: 🐛bug, ♻️refactor

#311 [공통] 씨앗 성장 로직 기능 추가
  Routinus/Routinus/Presentation/Home/Subviews/ContinuityView.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewModel.swift
  Routinus/Routinus/Presentation/MyPage/Subviews/MyPageProfileView.swift
Labels: ✨feature

#316 [전체 화면] UIRefreshControl 잔상 이슈 해결
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Extensions/UIScrollView+Extensions.swift
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/AuthImages/AuthImagesViewController.swift
  Routinus/Routinus/Presentation/Challenge/ChallengeViewController.swift
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: 🐛bug, ♻️refactor

#319 [검색 화면] SearchBar 관련 이슈 해결
  Routinus/Routinus/Presentation/Search/SearchViewController.swift
Labels: 🐛bug

#314 [홈 화면] 캘린더 셀 사이즈 깨지는 이슈 해결
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
Labels: 🐛bug

#323 [챌린지 생성 화면, 마이페이지 화면] 챌린지 수정 생성 or 닉네임 변경할 때 공백만 들어가는 경우 수정 or 생성 안되게 하기
  Routinus/Routinus/Presentation/Create/CreateViewModel.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
Labels: 🐛bug

#326 [홈 화면] 실행할 때 테마 적용하도록 수정
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
Labels: 🐛bug

#327 [공통] 가로모드, iPad 제한
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/AppDelegate.swift
Labels: ✨feature, 🐛bug

#328 [추가 화면] 키보드 높이만큼 여백 남아있는 이슈 해결
  Routinus/Routinus/Presentation/Create/CreateViewController.swift
Labels: 🐛bug

#330 [관리 화면] 헤더 클릭 시 crash 이슈 해결
  Routinus/Routinus/Presentation/Manage/Cells/ManageCollectionViewHeader.swift
  Routinus/Routinus/Presentation/Manage/ManageViewController.swift
Labels: 🐛bug

#331 [마이페이지] 개발자 정보 셀 클릭하면 GitHub 페이지로 연결
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/MyPageCoordinator.swift
  Routinus/Routinus/Presentation/MyPage/MyPageDeveloperViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewModel.swift
Labels: ✨feature

#325 [홈 화면] 챌린지 생성하고 요약스티커 반영 안되는 부분 수정
  Routinus/Routinus/Data/ChallengeRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/RoutinusNetwork/RoutinusNetwork.swift
Labels: 🐛bug

#335 [추가 화면, 인증 화면] 카메라 권한 없을 경우 Alert 띄우도록 구현
  Routinus/Routinus/Presentation/Auth/AuthViewController.swift
  Routinus/Routinus/Presentation/Form/FormViewController.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature

#336 [홈 화면] todayRoutine ProgressView -> CustomView 변경
  Routinus/Routinus/Presentation/Home/Cells/HomeRoutineTableViewCell.swift
Labels: 🐛bug, ♻️refactor
