Repository boostcampwm-2021/iOS03-Routinus, pull requests merged in 2021-12, with the labels that each got.

#338 [Tests] ViewModelTests코드 작성
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/RoutinusTests/MockDatas/AchievementFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/AchievementUpdatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/AuthFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ChallengeFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ChallengeUpdatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/HomeCreatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/HomeFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ImageFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ParticipationCreatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ParticipationFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/ParticipationFetchableUsecaseNilMock.swift
  Routinus/RoutinusTests/MockDatas/TodayRoutineFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/UserCreatableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/UserFetchableUsecaseMock.swift
  Routinus/RoutinusTests/MockDatas/UserUpdatableUsecaseMock.swift
  Routinus/RoutinusTests/ViewModelTests/ChallengeViewModelTests.swift
  Routinus/RoutinusTests/ViewModelTests/DetailViewModelTests.swift
  Routinus/RoutinusTests/ViewModelTests/HomeViewModelTests.swift
  Routinus/RoutinusTests/ViewModelTests/ManageViewModelTests.swift
  Routinus/RoutinusTests/ViewModelTests/MyPageViewModelTests.swift
  Routinus/RoutinusTests/ViewModelTests/SearchViewModelTests.swift
Labels: ✨feature

#342 [챌린지 추가 화면, 공통] 챌린지 이미지 변경 안되는 이슈 해결 및 햅팁 효과 주기
  Routinus/Routinus/Data/Repository/ImageRepository.swift
  Routinus/Routinus/Domain/Usecase/ChallengeCreateUsecase.swift
  Routinus/Routinus/Domain/Usecase/ImageUpdateUsecase.swift
  Routinus/Routinus/Extensions/UICollectionView+Extensions.swift
  Routinus/Routinus/Presentation/Detail/DetailViewController.swift
  Routinus/Routinus/Presentation/Detail/DetailViewModel.swift
  Routinus/Routinus/Presentation/Form/FormViewController.swift
  Routinus/Routinus/Presentation/Form/FormViewModel.swift
  Routinus/Routinus/Presentation/MyPage/MyPageViewController.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature, 🐛bug

#344 [관리 화면] endDate 비교 로직 수정
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
Labels: ♻️refactor

#339 [홈 화면] AchievementRateView 애니메이션 적용
  Routinus/Routinus/Presentation/Home/Cells/HomeRoutineTableViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
Labels: ✨feature

#345 [홈 화면] 캘린더 상세 정보 화면 추가
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/HomeCoordinator.swift
  Routinus/Routinus/Data/Repository/AuthRepository.swift
  Routinus/Routinus/Domain/Usecase/AuthFetchUsecase.swift
  Routinus/Routinus/Network/FirebaseService.swift
  Routinus/Routinus/Network/Query/AuthQuery.swift
  Routinus/Routinus/Presentation/Home/Cells/HomeCalendarDetailTableViewCell.swift
  Routinus/Routinus/Presentation/Home/Cells/HomeDateCollelctionViewCell.swift
  Routinus/Routinus/Presentation/Home/HomeCalendarDetailViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewController.swift
  Routinus/Routinus/Presentation/Home/HomeViewModel.swift
  Routinus/Routinus/Resources/en.lproj/Localizable.strings
  Routinus/Routinus/Resources/ko.lproj/Localizable.strings
Labels: ✨feature

#346 [상세 화면/인증 화면] PanView이름 수정, 애니메이션 수정
  Routinus/Routinus.xcodeproj/project.pbxproj
  Routinus/Routinus/Application/Coordinator/AuthCoordinator.swift
  Routinus/Routinus/Application/Coordinator/AuthImagesCoordinator.swift
  Routinus/Routinus/Application/Coordinator/DetailCoordinator.swift
  Routinus/Routinus/Presentation/Common/ImagePanViewController.swift
Labels: ♻️refactor

#347 [챌린지 화면, 나의 챌린지 화면] sort 로직 구현
  Routinus/Routinus/Domain/Usecase/ChallengeFetchUsecase.swift
  Routinus/Routinus/Network/DTO/AchievementDTO.swift
  Routinus/Routinus/Network/DTO/ChallengeDTO.swift
  Routinus/Routinus/Network/DTO/Fields.swift
  Routinus/Routinus/Network/DTO/ParticipationDTO.swift
  Routinus/Routinus/Network/DTO/UserDTO.swift
  Routinus/Routinus/Network/FirebaseService.swift
  Routinus/Routinus/Network/Query/ChallengeQuery.swift
Labels: ♻️refactor
